import type { Metadata } from "next";
import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/site.scss";
import Footer from "./_components/Footer";
import { AppProvider } from "./AppContext";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";

const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      localization={{
        signIn: {
          start: {
            title: "SIGN IN",
            subtitle: "Welcome to L.S.I 26",
          },
        },
        signUp: {
          start: {
            title: "SIGN UP",
            subtitle: "Welcome to L.S.I 26",
          },
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AppProvider>
            <Header />
            {children}
            <Footer />
          </AppProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
